demo_project/blog/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostDetailView,
    AboutPageView
)

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('about/', AboutPageView.as_view(), name='blog-about'),
    path('post/new', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail' )
]

demo_project/demo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo_project/user/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import (
    register,
    UserProfileDetailView,
    UserProfileUpdateView,
    UserPasswordChangeView
)


urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='user-login'),
    path('logout/', views.LogoutView.as_view(template_name='user/logout.html'), name='user-logout'),
    path('password_change/', UserPasswordChangeView.as_view(), name='user-password-change'),
    path('register/', register, name='user-register'),
    path('<int:pk>/profile/', UserProfileDetailView.as_view(), name='user-profile'),
    path('<int:pk>/profile/edit/', UserProfileUpdateView.as_view(), name='user-profile-edit')
]

demo_project/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', args=[self.pk])

demo_project/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(default='default.png', upload_to='user_images/')
    info = models.TextField(blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            img.thumbnail((300, 300))
            img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('user-profile', args=[self.pk])

demo_project/blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    TemplateView
)

from .models import Post


class AboutPageView(TemplateView):
    template_name = 'blog/about.html'


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    ordering = ['-date_posted']
    paginate_by = 4


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Create'
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'Edit'
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog-home')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDetailView(DetailView):
    model = Post

demo_project/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import TemplateView, DetailView, UpdateView
from django.urls import reverse_lazy

from .models import Profile


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user-login')
    else:
        form = UserCreationForm()

    return render(request, 'user/register.html', {'form': form})


class UserProfileDetailView(DetailView):
    model = Profile


class UserProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Profile
    fields = ['image', 'info']

    def test_func(self):
        profile_user = self.get_object().user
        if self.request.user == profile_user:
            return True
        return False


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'user/password_change_form.html'
    success_url = reverse_lazy('blog-home')

demo_project/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
<div class="box pt-3 pb-3 pr-4 pl-4">
  <h2>Django demo project</h2>
  <p class="pt-3">Just a simple django blog app.</p>
</div>
{% endblock content%}

demo_project/blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <title>Django demo</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog-home' %}">Django demo</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
            </div>

          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-10">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-2">
          <div class="list-group">
            {% if user.is_authenticated %}
              <a class="list-group-item list-group-item-action" href="{% url 'post-create' %}">New Post</a>
              <a class="list-group-item list-group-item-action" href="{% url 'user-profile' user.pk %}">Profile</a>
              <a class="list-group-item list-group-item-action" href="{% url 'user-logout' %}">Logout</a>
            {% else %}
              <a class="list-group-item list-group-item-action" href="{% url 'user-login' %}">Login</a>
              <a class="list-group-item list-group-item-action" href="{% url 'user-register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </main>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

demo_project/blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}
  {% for object in object_list %}
  <article class="media box pt-3 pb-4 pr-4 pl-2 mb-3">
    <img class="rounded-circle user-img mr-2" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="border-bottom">
        <a class="mr-2" href="{% url 'user-profile' object.author.pk %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
      </div>
        <h2 class="pt-2"><a href="{% url 'post-detail' object.id %}">{{ object.title }}</a></h2>
        <p class="pt-2">{{ object.content|truncatechars:250 }}</p>
    </div>
  </article>
  {% endfor %}

  {% if is_paginated %}
    <div class="mb-4 text-center">
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-primary" href="?page=1">First</a>
        <a class="btn btn-outline-primary" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-primary" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-primary" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-primary" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-primary" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    </div>
  {% endif %}
{% endblock content %}

demo_project/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
<div class="box pt-3 pb-3 pr-4 pl-4">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group border-bottom">
      <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
      <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
    </div>
  </form>
</div>
{% endblock content %}

demo_project/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<article class="media box pt-3 pb-4 pr-4 pl-2">
  <img class="rounded-circle user-img mr-2" src="{{ object.author.profile.image.url }}">
  <div class="media-body">
    <div class="border-bottom">
      <a class="mr-2" href="{% url 'user-profile' object.author.pk %}">{{ object.author }}</a>
      <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>

      {% if object.author == user %}
      <div class="pt-2 pb-2">
        <a class="btn btn-sm btn-outline-warning" href="{% url 'post-update' object.pk %}">Edit</a>
        <a class="btn btn-sm btn-outline-danger" href="{% url 'post-delete' object.pk %}">Delete</a>
      </div>
      {% endif %}
    </div>
      <h2 class="pt-2">{{ object.title }}</h2>
      <p class="pt-2">{{ object.content }}</p>
  </div>
</article>
{% endblock content %}

demo_project/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="box pt-3 pb-3 pr-4 pl-4">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group border-bottom">
      <h2>{{ action }} Post</h2>
    </fieldset>
    {{ form|crispy }}
    <button class="btn btn-outline-primary" type="submit">{{ action }}</button>
  </form>
</div>
{% endblock content %}

demo_project/user/templates/user/login.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="box pt-3 pb-3 pr-4 pl-4">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group border-bottom">
      <h2>Log in</h2>
    </fieldset>
    {{ form|crispy }}
    <button class="btn btn-outline-primary" type="submit">Login</button>
  </form>
</div>
{% endblock content %}

demo_project/user/templates/user/logout.html
{% extends "blog/base.html" %}

{% block content %}
<div class="box pt-3 pb-3 pr-4 pl-4">
  <h2>You have been logged out</h2>
  <div class="border-top pt-3">
    <small class="text-muted">
      <a href="{% url 'user-login' %}">Log In Again</a>
    </small>
  </div>
</div>
{% endblock content%}

demo_project/user/templates/user/password_change_form.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="box">
  <h2 class="border-bottom">Change password</h2>
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-primary" type="submit">Save</button>
    </div>
  </form>
</div>
{% endblock content %}

demo_project/user/templates/user/profile_detail.html
{% extends "blog/base.html" %}

{% block content %}
<article class="media box pt-3 pb-4 pr-4 pl-2">
  <img class="rounded-circle user-img mr-2" src="{{ object.image.url }}">
  <div class="media-body">
    <div class="border-bottom">
      {{ object.user.username }}
      <small class="ml-2 text-muted">{{ object.user.date_joined|date:"F d, Y" }}</small>

      {% if object.user == user %}
      <div class="pt-2 pb-2">
        <a class="btn btn-sm btn-outline-warning" href="{% url 'user-profile-edit' object.user.pk %}">Edit</a>
        <a class="btn btn-sm btn-outline-warning" href="{% url 'user-password-change' %}">Change password</a>
      </div>
      {% endif %}
    </div>
      <h2 class="pt-2">About me</h2>
      <p class="pt-2">{{ object.info }}</p>
  </div>
</article>
{% endblock content %}

demo_project/user/templates/user/profile_form.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="box">
  <h2 class="border-bottom">Edit Profile</h2>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-primary" type="submit">Save</button>
    </div>
  </form>
</div>
{% endblock content %}
{% block javascript %}
<script>
  // Just fix styling of image field
  $(function() {
    $('.custom-file-label').remove();
    $('.custom-file').removeClass('custom-file');
    $('#id_image').removeClass('clearablefileinput form-control custom-file-input').addClass('form-control-file');
  });
</script>
{% endblock javascript%}

demo_project/user/templates/user/register.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="box pt-3 pb-3 pr-4 pl-4">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group border-bottom">
      <h2>Register</h2>
    </fieldset>
    {{ form|crispy }}
    <button class="btn btn-outline-primary" type="submit">Create account</button>
  </form>
</div>
{% endblock content %}